package src;

public enum TaskArt {
    MESSAGE_SELF, MESSAGE_OTHERS, CR, CRR, SCC, SCCR, STU,
    CONNECTED_USERS,
    TIMER_EXPIRED, TIMER_START, TIMER_STOP, TIMER_TABLE_UPDATE_START, TIMER_TABLE_UPDATE_EXPIRED,
    CONNECT_TO, SEND_MESSAGE_TO, GET_CONNECTED_USERS
}
